### ISSUE TITLE
Hide the "Downloading data" dialogue

### ISSUE THREAD

**Issue by robinpaulson** [Gnonthgol/JOSM-continuos-download#13] opened 2015-01-01 12:04 UTC
As I pan across the map, the "downloading data" dialogue continuously pops up. Could this be changed to a "toast" or some other subtle mechanism for notifying the user? It's very distracting.

https://en.wikipedia.org/wiki/Toast_%28computing%29

Cheers

**Comment by Gnonthgol** [comment] 2015-01-01 19:20
Duplicate of #5

**Closed by Gnonthgol** 2015-01-01 19:20 UTC
